### ISSUE TITLE
Typing differentiation of an expression function and a declared function

### ISSUE THREAD

**Issue by Guilbertoliveira** [AlexcastroDev/real-world-typescript-usage#1]
A typing for an expression function was discussed in the document, but it could have examples in other scenarios.

**Comment by alexcastrodev** [comment]
@Guilbertoliveira Can you tell some of them ?

**Comment by Guilbertoliveira** [comment]
@AlexcastroDev yes, I myself tend to use more named declarative functions in my projects, there could also be an example using classes instead of functions.

``
export default function NamedComponent(props) { return ( )}
``

or

``
class ClassComponent extends Component { render() {return ()}}
``

Could use these examples ?

**Comment by alexcastrodev** [comment]
@Guilbertoliveira Look the pull request and check if this is enough

**Comment by Guilbertoliveira** [comment]
Yes i believe this will do, thanks xD
